export {
  createDefaultIntroductionQuestProgress,
  createDefaultQuestProgress,
  createDefaultSealedRelicQuestProgress,
  getAvailableQuests,
  getIntroductionQuestProgress,
  getQuestDefinition,
  getQuestProgress,
  getSealedRelicQuestProgress,
  hasCompletedIntroductionQuest,
  hasStartedIntroductionQuest,
  INTRODUCTION_QUEST_ID,
  isQuestAvailable,
  isQuestCompleted,
  normalizeQuestLog,
  QUEST_DEFINITIONS,
  SEALED_RELIC_QUEST_ID,
  type IntroductionQuestProgress,
  type IntroductionQuestStepId,
  type QuestDefinition,
  type QuestLog,
  type QuestProgress,
  type QuestStatus,
  type SealedRelicQuestProgress,
  type SealedRelicQuestStepId,
} from '@mmorpg/shared/quests/core';
