import {
  ITEM_DEFINITIONS as SHARED_ITEM_DEFINITIONS,
  getInventoryItemId,
  getInventoryItemQuantity,
  identifyAllRaidUnidentifiedInventoryEntries,
  parseInventoryItem,
  revealMatchedRaidUnidentifiedInventoryEntries,
  serializeInventoryItem,
  type BaseEquipmentSlot,
  type ConsumableItemId,
  type EquipmentItemId,
  type EquipmentItemSlot,
  type EquipmentSlot,
  type EquippableItemId,
  type GemItemId,
  type GemType,
  type ItemId,
  type ItemTier,
  type MiscItemId,
  type QuestItemId,
  type SharedItemDefinition,
} from '@mmorpg/shared';

export type {
  BaseEquipmentSlot,
  ConsumableItemId,
  EquipmentItemId,
  EquipmentItemSlot,
  EquipmentSlot,
  EquippableItemId,
  GemItemId,
  GemType,
  ItemId,
  ItemTier,
  MiscItemId,
  QuestItemId,
};

export type ItemDefinition = SharedItemDefinition & {
  textureKey: string;
  texturePath: string;
  iconTint?: string;
  iconRotationDeg?: number;
  iconScale?: number;
  compactIconScale?: number;
  equippedAnchorHand?: 'left' | 'right';
  equippedOffsetX?: number;
  equippedOffsetY?: number;
  equippedOriginX?: number;
  equippedOriginY?: number;
  worldRotationDeg?: number;
  worldScale?: number;
  worldEffects?: Array<{
    textureKey: string;
    texturePath: string;
    frameWidth?: number;
    frameHeight?: number;
    frameCount?: number;
    frameDurationMs?: number;
    offsetX: number;
    offsetY: number;
    scale?: number;
    alpha?: number;
    rotationDeg?: number;
  }>;
};

type RawItemDefinition = Omit<ItemDefinition, 'iconPath'> & {
  iconPath?: string;
};

const RAW_ITEM_DEFINITIONS: Record<ItemId, RawItemDefinition> = {
  wood_staff: {
    id: 'wood_staff',
    type: 'equipment',
    name: 'Wood Staff',
    value: 90,
    slot: 'weapon',
    tier: 1,
    socketType: 'weapon',
    tooltipStats: ['Melee weapon', 'Astral catalyst', '1 gem socket'],
    textureKey: 'item-wood-staff',
    texturePath: '/items/equipment/wood_staff.png',
    socketCount: 1,
    iconScale: 0.9,
    compactIconScale: 0.9,
    equippedAnchorHand: 'right',
    equippedOffsetX: 0,
    equippedOffsetY: 1,
    equippedOriginX: 0.5,
    equippedOriginY: 0.78,
    worldRotationDeg: 0,
    worldScale: 1.35,
  },
  wood_staff_t2: {
    id: 'wood_staff_t2',
    type: 'equipment',
    name: 'Wood Staff (Rare)',
    value: 90,
    slot: 'weapon',
    tier: 2,
    socketType: 'weapon',
    tooltipStats: ['Melee weapon', 'Astral catalyst', '2 gem sockets', 'Rare chest drop'],
    textureKey: 'item-wood-staff-t2',
    texturePath: '/items/equipment/wood_staff.png',
    socketCount: 2,
    iconScale: 0.9,
    compactIconScale: 0.9,
    equippedAnchorHand: 'right',
    equippedOffsetX: 0,
    equippedOffsetY: 1,
    equippedOriginX: 0.5,
    equippedOriginY: 0.78,
    worldRotationDeg: 0,
    worldScale: 1.35,
  },
  wood_staff_t3: {
    id: 'wood_staff_t3',
    type: 'equipment',
    name: 'Wood Staff (Very Rare)',
    value: 90,
    slot: 'weapon',
    tier: 3,
    socketType: 'weapon',
    tooltipStats: ['Melee weapon', 'Astral catalyst', '3 gem sockets', 'Very rare chest drop'],
    textureKey: 'item-wood-staff-t3',
    texturePath: '/items/equipment/wood_staff.png',
    socketCount: 3,
    iconScale: 0.9,
    compactIconScale: 0.9,
    equippedAnchorHand: 'right',
    equippedOffsetX: 0,
    equippedOffsetY: 1,
    equippedOriginX: 0.5,
    equippedOriginY: 0.78,
    worldRotationDeg: 0,
    worldScale: 1.35,
  },
  fire_staff: {
    id: 'fire_staff',
    type: 'equipment',
    name: 'Fire Staff',
    value: 140,
    slot: 'weapon',
    tier: 1,
    socketType: 'weapon',
    tooltipStats: ['Fire catalyst', 'Casts fireball', '3 gem sockets'],
    textureKey: 'item-fire-staff',
    texturePath: '/items/equipment/default-staff.png',
    socketCount: 3,
    iconScale: 0.9,
    compactIconScale: 0.9,
    equippedAnchorHand: 'right',
    equippedOffsetX: 0,
    equippedOffsetY: 1,
    equippedOriginX: 0.5,
    equippedOriginY: 0.78,
    worldRotationDeg: 0,
    worldScale: 1.35,
  },
  fire_robe: {
    id: 'fire_robe',
    type: 'equipment',
    name: 'Fire Robe',
    value: 120,
    slot: 'body',
    tier: 1,
    socketType: 'armor',
    tooltipStats: ['Body armor', '1 gem socket'],
    textureKey: 'item-fire-robe',
    texturePath: '/character/equipment/fire_robe/fire_robe_idle.png',
    socketCount: 1,
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_robe_t2: {
    id: 'fire_robe_t2',
    type: 'equipment',
    name: 'Fire Robe (Rare)',
    value: 120,
    slot: 'body',
    tier: 2,
    socketType: 'armor',
    tooltipStats: ['Body armor', '2 gem sockets', 'Rare chest drop'],
    textureKey: 'item-fire-robe-t2',
    texturePath: '/character/equipment/fire_robe/fire_robe_idle.png',
    socketCount: 2,
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_robe_t3: {
    id: 'fire_robe_t3',
    type: 'equipment',
    name: 'Fire Robe (Very Rare)',
    value: 120,
    slot: 'body',
    tier: 3,
    socketType: 'armor',
    tooltipStats: ['Body armor', '3 gem sockets', 'Very rare chest drop'],
    textureKey: 'item-fire-robe-t3',
    texturePath: '/character/equipment/fire_robe/fire_robe_idle.png',
    socketCount: 3,
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_trail_gem: {
    id: 'fire_trail_gem',
    type: 'gem',
    name: 'Fire Trail Gem',
    value: 55,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Fireball leaves burning trail', 'Trail lasts 5s', '+0.2s cast time'],
    textureKey: 'item-fire-trail-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_shatter_gem: {
    id: 'fire_shatter_gem',
    type: 'gem',
    name: 'Fire Shatter Gem',
    value: 70,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Fireball bursts into 9 shards', 'Shards deal no direct damage'],
    textureKey: 'item-fire-shatter-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_return_gem: {
    id: 'fire_return_gem',
    type: 'gem',
    name: 'Fire Return Gem',
    value: 50,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Projectiles that miss return to cast point'],
    textureKey: 'item-fire-return-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_bounce_gem: {
    id: 'fire_bounce_gem',
    type: 'gem',
    name: 'Fire Bounce Gem',
    value: 45,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', '+2 wall bounces per gem'],
    textureKey: 'item-fire-bounce-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_longshot_gem: {
    id: 'fire_longshot_gem',
    type: 'gem',
    name: 'Fire Longshot Gem',
    value: 65,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', '+200% projectile range', 'Damage falls from 100% to 0% over distance'],
    textureKey: 'item-fire-longshot-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_split_gem: {
    id: 'fire_split_gem',
    type: 'gem',
    name: 'Fire Split Gem',
    value: 60,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Fireball becomes 2 smaller shots', 'Damage is split between them'],
    textureKey: 'item-fire-split-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_range_gem: {
    id: 'fire_range_gem',
    type: 'gem',
    name: 'Fire Range Gem',
    value: 50,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', '+25% cast range', '+25% fireball cooldown'],
    textureKey: 'item-fire-range-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  cast_speed_gem: {
    id: 'cast_speed_gem',
    type: 'gem',
    name: 'Cast Speed Gem',
    value: 70,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', '-35% cast time', '-12% direct damage'],
    textureKey: 'item-cast-speed-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  pierce_gem: {
    id: 'pierce_gem',
    type: 'gem',
    name: 'Pierce Gem',
    value: 65,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Projectile pierces 2 targets', '-18% direct damage'],
    textureKey: 'item-pierce-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  chain_gem: {
    id: 'chain_gem',
    type: 'gem',
    name: 'Chain Gem',
    value: 75,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Projectile chains 2 times', '-15% direct damage'],
    textureKey: 'item-chain-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  homing_gem: {
    id: 'homing_gem',
    type: 'gem',
    name: 'Homing Gem',
    value: 70,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Projectile seeks nearby targets', '-10% projectile speed'],
    textureKey: 'item-homing-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  area_gem: {
    id: 'area_gem',
    type: 'gem',
    name: 'Area Gem',
    value: 55,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Impact deals splash damage', '-20% direct damage'],
    textureKey: 'item-area-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  duration_gem: {
    id: 'duration_gem',
    type: 'gem',
    name: 'Duration Gem',
    value: 50,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', '+50% burn and trail duration'],
    textureKey: 'item-duration-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  knockback_gem: {
    id: 'knockback_gem',
    type: 'gem',
    name: 'Knockback Gem',
    value: 45,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Hit pushes targets back'],
    textureKey: 'item-knockback-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  lifesteal_gem: {
    id: 'lifesteal_gem',
    type: 'gem',
    name: 'Lifesteal Gem',
    value: 90,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Heal for 10% of direct damage dealt'],
    textureKey: 'item-lifesteal-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  execution_gem: {
    id: 'execution_gem',
    type: 'gem',
    name: 'Execution Gem',
    value: 80,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', '+50% damage to targets below 30% HP'],
    textureKey: 'item-execution-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  critical_gem: {
    id: 'critical_gem',
    type: 'gem',
    name: 'Critical Gem',
    value: 85,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', '20% chance to crit for 200% damage'],
    textureKey: 'item-critical-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_spread_gem: {
    id: 'fire_spread_gem',
    type: 'gem',
    name: 'Fire Spread Gem',
    value: 65,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Fires 3 projectiles in a fan', '-40% damage per projectile'],
    textureKey: 'item-fire-spread-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_burst_gem: {
    id: 'fire_burst_gem',
    type: 'gem',
    name: 'Fire Burst Gem',
    value: 60,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Fires 3 rapid shots', '-60% damage per shot', '+50% cooldown'],
    textureKey: 'item-fire-burst-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_nova_impact_gem: {
    id: 'fire_nova_impact_gem',
    type: 'gem',
    name: 'Impact Nova Gem',
    value: 75,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'On hit: ring of 6 mini-projectiles', 'Mini-projectiles deal 30% damage', '-25% direct damage'],
    textureKey: 'item-fire-nova-impact-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_spiral_gem: {
    id: 'fire_spiral_gem',
    type: 'gem',
    name: 'Fire Spiral Gem',
    value: 55,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Projectile spirals in flight', 'Covers wider area', '-15% projectile speed'],
    textureKey: 'item-fire-spiral-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_fork_gem: {
    id: 'fire_fork_gem',
    type: 'gem',
    name: 'Fire Fork Gem',
    value: 70,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Splits into 2 at half range', 'Forks deal 50% damage'],
    textureKey: 'item-fire-fork-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_orbit_gem: {
    id: 'fire_orbit_gem',
    type: 'gem',
    name: 'Fire Orbit Gem',
    value: 60,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Projectile orbits caster before launch', '0.5s delay before flight'],
    textureKey: 'item-fire-orbit-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_aftershock_gem: {
    id: 'fire_aftershock_gem',
    type: 'gem',
    name: 'Aftershock Gem',
    value: 70,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'Second explosion after 0.3s', 'Aftershock deals 50% damage', '-15% direct damage'],
    textureKey: 'item-fire-aftershock-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_clone_gem: {
    id: 'fire_clone_gem',
    type: 'gem',
    name: 'Fire Clone Gem',
    value: 80,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['wood_staff', 'fire_staff'],
    tooltipStats: ['Socket into staff', 'On hit: clone flies to nearest enemy', 'Clone deals 40% damage', '-20% direct damage'],
    textureKey: 'item-fire-clone-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  healing_potion: {
    id: 'healing_potion',
    type: 'consumable',
    name: 'Healing Potion',
    value: 12,
    tooltipStats: ['Restores 20 HP over 10s', 'Cooldown: 20s', 'Stacks to 5'],
    textureKey: 'item-healing-potion',
    texturePath: '/pack/potion and poison asset pack/Crimson Health Elixir.png',
    stackable: true,
    maxStack: 5,
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  teleport_scroll: {
    id: 'teleport_scroll',
    type: 'consumable',
    name: 'Teleport Scroll',
    value: 32,
    tooltipStats: ['3s use time', 'Teleports to random floor tile', 'Stacks to 1'],
    textureKey: 'item-teleport-scroll',
    texturePath: '/items/scroll.png',
    stackable: true,
    maxStack: 1,
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  wood: {
    id: 'wood',
    type: 'misc',
    name: 'Wood',
    value: 2,
    tooltipStats: ['Common loot item', 'Can be found in chests', 'Stacks to 99'],
    textureKey: 'item-wood-resource',
    texturePath: '/items/resources/wood_1.png',
    stackable: true,
    maxStack: 99,
    iconTint: '#9b6a3a',
    iconRotationDeg: 90,
    iconScale: 0.78,
    compactIconScale: 0.72,
  },
  stone: {
    id: 'stone',
    type: 'misc',
    name: 'Stone',
    value: 2,
    tooltipStats: ['Common loot item', 'Solid crafting material', 'Stacks to 99'],
    textureKey: 'item-stone-resource',
    texturePath: '/items/resources/stone-16x16.png',
    stackable: true,
    maxStack: 99,
    iconScale: 0.9,
    compactIconScale: 0.86,
  },
  fire_essence: {
    id: 'fire_essence',
    type: 'misc',
    name: 'Fire Essence',
    value: 6,
    tooltipStats: ['Elemental crafting reagent', 'Warm to the touch', 'Stacks to 99'],
    textureKey: 'item-fire-essence',
    texturePath: '/items/resources/fire-essence-16x16.png',
    stackable: true,
    maxStack: 99,
    iconScale: 0.95,
    compactIconScale: 0.92,
  },
  lightning_essence: {
    id: 'lightning_essence',
    type: 'misc',
    name: 'Lightning Essence',
    value: 6,
    tooltipStats: ['Elemental crafting reagent', 'Crackles with static', 'Stacks to 99'],
    textureKey: 'item-lightning-essence',
    texturePath: '/items/resources/lightning-essence-16x16.png',
    stackable: true,
    maxStack: 99,
    iconScale: 0.95,
    compactIconScale: 0.92,
  },
  ice_essence: {
    id: 'ice_essence',
    type: 'misc',
    name: 'Ice Essence',
    value: 6,
    tooltipStats: ['Elemental crafting reagent', 'Cold and pristine', 'Stacks to 99'],
    textureKey: 'item-ice-essence',
    texturePath: '/items/resources/ice-essence-16x16.png',
    stackable: true,
    maxStack: 99,
    iconScale: 0.95,
    compactIconScale: 0.92,
  },
  darkness_essence: {
    id: 'darkness_essence',
    type: 'misc',
    name: 'Darkness Essence',
    value: 6,
    tooltipStats: ['Elemental crafting reagent', 'Swallows nearby light', 'Stacks to 99'],
    textureKey: 'item-darkness-essence',
    texturePath: '/items/resources/darkness-essence-16x16.png',
    stackable: true,
    maxStack: 99,
    iconScale: 0.95,
    compactIconScale: 0.92,
  },
  void_essence: {
    id: 'void_essence',
    type: 'misc',
    name: 'Void Essence',
    value: 6,
    tooltipStats: ['Elemental crafting reagent', 'Hums with empty space', 'Stacks to 99'],
    textureKey: 'item-void-essence',
    texturePath: '/items/resources/void-essence-16x16.png',
    stackable: true,
    maxStack: 99,
    iconScale: 0.95,
    compactIconScale: 0.92,
  },
  sealed_relic: {
    id: 'sealed_relic',
    type: 'quest',
    name: 'Sealed Relic',
    value: 0,
    tooltipStats: ['Quest item', 'Bring it back to the Old Mage', 'Cannot be sold or used'],
    textureKey: 'item-sealed-relic',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 1,
    compactIconScale: 0.95,
  },
};

type ItemVisualOverride = Pick<ItemDefinition, 'texturePath' | 'iconTint'>;

const ITEM_VISUAL_OVERRIDES: Partial<Record<ItemId, ItemVisualOverride>> = {
  fire_trail_gem: {
    texturePath: '/sprites/gems/round-faceted-white.png',
    iconTint: '#ff8a3d',
  },
  fire_shatter_gem: {
    texturePath: '/sprites/gems/square-faceted-white.png',
    iconTint: '#ffbf69',
  },
  fire_return_gem: {
    texturePath: '/sprites/gems/oval-faceted-white.png',
    iconTint: '#ff6b6b',
  },
  fire_bounce_gem: {
    texturePath: '/sprites/gems/round-cabochon-white.png',
    iconTint: '#ff9f1c',
  },
  fire_longshot_gem: {
    texturePath: '/sprites/gems/oval-cabochon-white.png',
    iconTint: '#ffd166',
  },
  fire_split_gem: {
    texturePath: '/sprites/gems/square-cabochon-white.png',
    iconTint: '#ff8fab',
  },
  fire_range_gem: {
    texturePath: '/sprites/gems/oval-cabochon-white.png',
    iconTint: '#ffe66d',
  },
  cast_speed_gem: {
    texturePath: '/sprites/gems/round-faceted-white.png',
    iconTint: '#60c2ff',
  },
  pierce_gem: {
    texturePath: '/sprites/gems/square-faceted-white.png',
    iconTint: '#6ee7b7',
  },
  chain_gem: {
    texturePath: '/sprites/gems/oval-faceted-white.png',
    iconTint: '#7dd3fc',
  },
  homing_gem: {
    texturePath: '/sprites/gems/round-cabochon-white.png',
    iconTint: '#38bdf8',
  },
  area_gem: {
    texturePath: '/sprites/gems/round-cabochon-white.png',
    iconTint: '#c084fc',
  },
  duration_gem: {
    texturePath: '/sprites/gems/oval-cabochon-white.png',
    iconTint: '#93c5fd',
  },
  knockback_gem: {
    texturePath: '/sprites/gems/square-cabochon-white.png',
    iconTint: '#a3e635',
  },
  lifesteal_gem: {
    texturePath: '/sprites/gems/round-faceted-white.png',
    iconTint: '#f43f5e',
  },
  execution_gem: {
    texturePath: '/sprites/gems/square-faceted-white.png',
    iconTint: '#f59e0b',
  },
  critical_gem: {
    texturePath: '/sprites/gems/oval-faceted-white.png',
    iconTint: '#ec4899',
  },
  fire_spread_gem: {
    texturePath: '/sprites/gems/square-cabochon-white.png',
    iconTint: '#fb923c',
  },
  fire_burst_gem: {
    texturePath: '/sprites/gems/round-faceted-white.png',
    iconTint: '#f97316',
  },
  fire_nova_impact_gem: {
    texturePath: '/sprites/gems/round-cabochon-white.png',
    iconTint: '#ff7f50',
  },
  fire_spiral_gem: {
    texturePath: '/sprites/gems/oval-faceted-white.png',
    iconTint: '#22d3ee',
  },
  fire_fork_gem: {
    texturePath: '/sprites/gems/square-faceted-white.png',
    iconTint: '#fca5a5',
  },
  fire_orbit_gem: {
    texturePath: '/sprites/gems/round-cabochon-white.png',
    iconTint: '#818cf8',
  },
  fire_aftershock_gem: {
    texturePath: '/sprites/gems/oval-cabochon-white.png',
    iconTint: '#facc15',
  },
  fire_clone_gem: {
    texturePath: '/sprites/gems/square-faceted-white.png',
    iconTint: '#a78bfa',
  },
  sealed_relic: {
    texturePath: '/sprites/gems/oval-faceted-white.png',
    iconTint: '#e7c76c',
  },
};

export const ITEM_DEFINITIONS: Record<ItemId, ItemDefinition> = Object.fromEntries(
  (Object.keys(RAW_ITEM_DEFINITIONS) as ItemId[]).map((itemId) => {
    const localDefinition = RAW_ITEM_DEFINITIONS[itemId];
    const sharedDefinition = SHARED_ITEM_DEFINITIONS[itemId];
    const visualOverride = ITEM_VISUAL_OVERRIDES[itemId];

    return [
      itemId,
      {
        ...localDefinition,
        texturePath: visualOverride?.texturePath ?? localDefinition.texturePath,
        iconTint: visualOverride?.iconTint,
        name: sharedDefinition.name,
        type: sharedDefinition.type,
        value: sharedDefinition.value,
        iconPath: visualOverride?.texturePath ?? sharedDefinition.iconPath,
        slot: sharedDefinition.slot,
        tier: sharedDefinition.tier,
        socketType: sharedDefinition.socketType,
        gemType: sharedDefinition.gemType,
        socketableInto: sharedDefinition.socketableInto,
        socketCount: sharedDefinition.socketCount,
        tooltipStats: [...sharedDefinition.tooltipStats],
        stackable: sharedDefinition.stackable,
        maxStack: sharedDefinition.maxStack,
        fireResistancePercent: sharedDefinition.fireResistancePercent,
      },
    ];
  }),
) as Record<ItemId, ItemDefinition>;

export const EQUIPMENT_ITEMS = ITEM_DEFINITIONS as Record<ItemId, ItemDefinition>;
export {
  getInventoryItemId,
  getInventoryItemQuantity,
  identifyAllRaidUnidentifiedInventoryEntries,
  parseInventoryItem,
  revealMatchedRaidUnidentifiedInventoryEntries,
  serializeInventoryItem,
};

export function getItemValue(itemId: ItemId, quantity = 1) {
  return ITEM_DEFINITIONS[itemId].value * Math.max(1, quantity);
}

export function getItemIconTint(itemId: ItemId | string | null | undefined) {
  if (!itemId || !(itemId in ITEM_DEFINITIONS)) {
    return null;
  }

  return ITEM_DEFINITIONS[itemId as ItemId].iconTint ?? null;
}

export function getEquipmentGemSlotId(slot: BaseEquipmentSlot, index: number): EquipmentSlot {
  return `${slot}-gem-${index + 1}` as EquipmentSlot;
}

export function getEquipmentGemSlotIds(slot: BaseEquipmentSlot, socketCount: number) {
  return Array.from({ length: Math.max(0, socketCount) }, (_, index) => getEquipmentGemSlotId(slot, index));
}

export function isEquipmentGemSlot(slot: EquipmentSlot): boolean {
  return /^(head|body|weapon)-gem-\d+$/.test(slot);
}

export function getBaseEquipmentSlot(slot: EquipmentSlot): BaseEquipmentSlot | null {
  if (isEquipmentGemSlot(slot)) {
    return slot.replace(/-gem-\d+$/, '') as BaseEquipmentSlot;
  }

  return slot as BaseEquipmentSlot;
}

