import {
  ITEM_DEFINITIONS as SHARED_ITEM_DEFINITIONS,
  getInventoryItemId,
  getInventoryItemQuantity,
  parseInventoryItem,
  serializeInventoryItem,
  type BaseEquipmentSlot,
  type ConsumableItemId,
  type EquipmentItemId,
  type EquipmentItemSlot,
  type EquipmentSlot,
  type EquippableItemId,
  type GemItemId,
  type GemType,
  type ItemId,
  type ItemTier,
  type QuestItemId,
  type SharedItemDefinition,
} from '@mmorpg/shared';

export type {
  BaseEquipmentSlot,
  ConsumableItemId,
  EquipmentItemId,
  EquipmentItemSlot,
  EquipmentSlot,
  EquippableItemId,
  GemItemId,
  GemType,
  ItemId,
  ItemTier,
  QuestItemId,
};

export type ItemDefinition = SharedItemDefinition & {
  textureKey: string;
  texturePath: string;
  iconRotationDeg?: number;
  iconScale?: number;
  compactIconScale?: number;
  equippedOffsetX?: number;
  equippedOffsetY?: number;
  worldRotationDeg?: number;
  worldScale?: number;
  worldEffects?: Array<{
    textureKey: string;
    texturePath: string;
    frameWidth?: number;
    frameHeight?: number;
    frameCount?: number;
    frameDurationMs?: number;
    offsetX: number;
    offsetY: number;
    scale?: number;
    alpha?: number;
    rotationDeg?: number;
  }>;
};

type RawItemDefinition = Omit<ItemDefinition, 'iconPath'> & {
  iconPath?: string;
};

const RAW_ITEM_DEFINITIONS: Record<ItemId, RawItemDefinition> = {
  default_staff: {
    id: 'default_staff',
    type: 'equipment',
    name: 'Default Staff',
    value: 90,
    slot: 'weapon',
    tier: 3,
    socketType: 'weapon',
    tooltipStats: ['Unlocks Fireball', '3 gem sockets'],
    textureKey: 'item-default-staff',
    texturePath: '/items/equipment/default-staff.png',
    socketCount: 3,
    iconScale: 0.9,
    compactIconScale: 0.9,
    equippedOffsetX: 3,
    equippedOffsetY: 0,
    worldRotationDeg: -45,
    worldScale: 3,
    worldEffects: [
      {
        textureKey: 'effect-fire-sheet',
        texturePath: '/items/equipment/effects/fire-effect-sheet.png',
        frameWidth: 32,
        frameHeight: 32,
        frameCount: 4,
        frameDurationMs: 90,
        offsetX: 11,
        offsetY: -16,
        scale: 0.3,
        alpha: 0.95,
        rotationDeg: 0,
      },
    ],
  },
  fire_robe: {
    id: 'fire_robe',
    type: 'equipment',
    name: 'Fire Robe',
    value: 120,
    slot: 'body',
    tier: 2,
    socketType: 'armor',
    tooltipStats: ['Body armor', '3 gem sockets'],
    textureKey: 'equip-fire-robe-idle',
    texturePath: '/character/equipment/fire_robe/fire_robe_idle.png',
    socketCount: 3,
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_trail_gem: {
    id: 'fire_trail_gem',
    type: 'gem',
    name: 'Fire Trail Gem',
    value: 55,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Fireball leaves burning trail', 'Trail lasts 5s', '+0.2s cast time'],
    textureKey: 'item-fire-trail-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_shatter_gem: {
    id: 'fire_shatter_gem',
    type: 'gem',
    name: 'Fire Shatter Gem',
    value: 70,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Fireball bursts into 9 shards', 'Shards deal no direct damage'],
    textureKey: 'item-fire-shatter-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_return_gem: {
    id: 'fire_return_gem',
    type: 'gem',
    name: 'Fire Return Gem',
    value: 50,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Projectiles that miss return to cast point'],
    textureKey: 'item-fire-return-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_bounce_gem: {
    id: 'fire_bounce_gem',
    type: 'gem',
    name: 'Fire Bounce Gem',
    value: 45,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', '+2 wall bounces per gem'],
    textureKey: 'item-fire-bounce-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_longshot_gem: {
    id: 'fire_longshot_gem',
    type: 'gem',
    name: 'Fire Longshot Gem',
    value: 65,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', '+200% projectile range', 'Damage falls from 100% to 0% over distance'],
    textureKey: 'item-fire-longshot-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_split_gem: {
    id: 'fire_split_gem',
    type: 'gem',
    name: 'Fire Split Gem',
    value: 60,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Fireball becomes 2 smaller shots', 'Damage is split between them'],
    textureKey: 'item-fire-split-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_range_gem: {
    id: 'fire_range_gem',
    type: 'gem',
    name: 'Fire Range Gem',
    value: 50,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', '+25% cast range', '+25% fireball cooldown'],
    textureKey: 'item-fire-range-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  cast_speed_gem: {
    id: 'cast_speed_gem',
    type: 'gem',
    name: 'Cast Speed Gem',
    value: 70,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', '-35% cast time', '-12% direct damage'],
    textureKey: 'item-cast-speed-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  pierce_gem: {
    id: 'pierce_gem',
    type: 'gem',
    name: 'Pierce Gem',
    value: 65,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Projectile pierces 2 targets', '-18% direct damage'],
    textureKey: 'item-pierce-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  chain_gem: {
    id: 'chain_gem',
    type: 'gem',
    name: 'Chain Gem',
    value: 75,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Projectile chains 2 times', '-15% direct damage'],
    textureKey: 'item-chain-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  homing_gem: {
    id: 'homing_gem',
    type: 'gem',
    name: 'Homing Gem',
    value: 70,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Projectile seeks nearby targets', '-10% projectile speed'],
    textureKey: 'item-homing-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  area_gem: {
    id: 'area_gem',
    type: 'gem',
    name: 'Area Gem',
    value: 55,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Impact deals splash damage', '-20% direct damage'],
    textureKey: 'item-area-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  duration_gem: {
    id: 'duration_gem',
    type: 'gem',
    name: 'Duration Gem',
    value: 50,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', '+50% burn and trail duration'],
    textureKey: 'item-duration-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  knockback_gem: {
    id: 'knockback_gem',
    type: 'gem',
    name: 'Knockback Gem',
    value: 45,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Hit pushes targets back'],
    textureKey: 'item-knockback-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  lifesteal_gem: {
    id: 'lifesteal_gem',
    type: 'gem',
    name: 'Lifesteal Gem',
    value: 90,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Heal for 10% of direct damage dealt'],
    textureKey: 'item-lifesteal-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  execution_gem: {
    id: 'execution_gem',
    type: 'gem',
    name: 'Execution Gem',
    value: 80,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', '+50% damage to targets below 30% HP'],
    textureKey: 'item-execution-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  critical_gem: {
    id: 'critical_gem',
    type: 'gem',
    name: 'Critical Gem',
    value: 85,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', '20% chance to crit for 200% damage'],
    textureKey: 'item-critical-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_spread_gem: {
    id: 'fire_spread_gem',
    type: 'gem',
    name: 'Fire Spread Gem',
    value: 65,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Fires 3 projectiles in a fan', '-40% damage per projectile'],
    textureKey: 'item-fire-spread-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_burst_gem: {
    id: 'fire_burst_gem',
    type: 'gem',
    name: 'Fire Burst Gem',
    value: 60,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Fires 3 rapid shots', '-60% damage per shot', '+50% cooldown'],
    textureKey: 'item-fire-burst-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_nova_impact_gem: {
    id: 'fire_nova_impact_gem',
    type: 'gem',
    name: 'Impact Nova Gem',
    value: 75,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'On hit: ring of 6 mini-projectiles', 'Mini-projectiles deal 30% damage', '-25% direct damage'],
    textureKey: 'item-fire-nova-impact-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_spiral_gem: {
    id: 'fire_spiral_gem',
    type: 'gem',
    name: 'Fire Spiral Gem',
    value: 55,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Projectile spirals in flight', 'Covers wider area', '-15% projectile speed'],
    textureKey: 'item-fire-spiral-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_fork_gem: {
    id: 'fire_fork_gem',
    type: 'gem',
    name: 'Fire Fork Gem',
    value: 70,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Splits into 2 at half range', 'Forks deal 50% damage'],
    textureKey: 'item-fire-fork-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_orbit_gem: {
    id: 'fire_orbit_gem',
    type: 'gem',
    name: 'Fire Orbit Gem',
    value: 60,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Projectile orbits caster before launch', '0.5s delay before flight'],
    textureKey: 'item-fire-orbit-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_aftershock_gem: {
    id: 'fire_aftershock_gem',
    type: 'gem',
    name: 'Aftershock Gem',
    value: 70,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'Second explosion after 0.3s', 'Aftershock deals 50% damage', '-15% direct damage'],
    textureKey: 'item-fire-aftershock-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  fire_clone_gem: {
    id: 'fire_clone_gem',
    type: 'gem',
    name: 'Fire Clone Gem',
    value: 80,
    slot: 'weapon-gem-1',
    gemType: 'weapon',
    socketableInto: ['default_staff'],
    tooltipStats: ['Socket into staff', 'On hit: clone flies to nearest enemy', 'Clone deals 40% damage', '-20% direct damage'],
    textureKey: 'item-fire-clone-gem',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  healing_potion: {
    id: 'healing_potion',
    type: 'consumable',
    name: 'Healing Potion',
    value: 12,
    tooltipStats: ['Restores 20 HP over 10s', 'Cooldown: 20s', 'Stacks to 5'],
    textureKey: 'item-healing-potion',
    texturePath: '/pack/potion and poison asset pack/Crimson Health Elixir.png',
    stackable: true,
    maxStack: 5,
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  teleport_scroll: {
    id: 'teleport_scroll',
    type: 'consumable',
    name: 'Teleport Scroll',
    value: 32,
    tooltipStats: ['3s use time', 'Teleports to random floor tile', 'Stacks to 1'],
    textureKey: 'item-teleport-scroll',
    texturePath: '/items/scroll.png',
    stackable: true,
    maxStack: 1,
    iconScale: 0.9,
    compactIconScale: 0.9,
  },
  sealed_relic: {
    id: 'sealed_relic',
    type: 'quest',
    name: 'Sealed Relic',
    value: 0,
    tooltipStats: ['Quest item', 'Bring it back to the Old Mage', 'Cannot be sold or used'],
    textureKey: 'item-sealed-relic',
    texturePath: '/items/gems/gem_basic.png',
    iconScale: 1,
    compactIconScale: 0.95,
  },
};

export const ITEM_DEFINITIONS: Record<ItemId, ItemDefinition> = Object.fromEntries(
  (Object.keys(RAW_ITEM_DEFINITIONS) as ItemId[]).map((itemId) => {
    const localDefinition = RAW_ITEM_DEFINITIONS[itemId];
    const sharedDefinition = SHARED_ITEM_DEFINITIONS[itemId];

    return [
      itemId,
      {
        ...localDefinition,
        name: sharedDefinition.name,
        type: sharedDefinition.type,
        value: sharedDefinition.value,
        iconPath: sharedDefinition.iconPath,
        slot: sharedDefinition.slot,
        tier: sharedDefinition.tier,
        socketType: sharedDefinition.socketType,
        gemType: sharedDefinition.gemType,
        socketableInto: sharedDefinition.socketableInto,
        socketCount: sharedDefinition.socketCount,
        tooltipStats: [...sharedDefinition.tooltipStats],
        stackable: sharedDefinition.stackable,
        maxStack: sharedDefinition.maxStack,
        fireResistancePercent: sharedDefinition.fireResistancePercent,
      },
    ];
  }),
) as Record<ItemId, ItemDefinition>;

export const EQUIPMENT_ITEMS = ITEM_DEFINITIONS as Record<ItemId, ItemDefinition>;
export {
  getInventoryItemId,
  getInventoryItemQuantity,
  parseInventoryItem,
  serializeInventoryItem,
};

export function getItemValue(itemId: ItemId, quantity = 1) {
  return ITEM_DEFINITIONS[itemId].value * Math.max(1, quantity);
}

export function getEquipmentGemSlotId(slot: BaseEquipmentSlot, index: number): EquipmentSlot {
  return `${slot}-gem-${index + 1}` as EquipmentSlot;
}

export function getEquipmentGemSlotIds(slot: BaseEquipmentSlot, socketCount: number) {
  return Array.from({ length: Math.max(0, socketCount) }, (_, index) => getEquipmentGemSlotId(slot, index));
}

export function isEquipmentGemSlot(slot: EquipmentSlot): boolean {
  return /^(head|body|weapon)-gem-\d+$/.test(slot);
}

export function getBaseEquipmentSlot(slot: EquipmentSlot): BaseEquipmentSlot | null {
  if (isEquipmentGemSlot(slot)) {
    return slot.replace(/-gem-\d+$/, '') as BaseEquipmentSlot;
  }

  return slot as BaseEquipmentSlot;
}
